echo "ROS เวอร์ชันที่ใช้ = "$ROS_VERSION
echo "ROS_PYTHON_VERSION = "$ROS_PYTHON_VERSION
echo "ROS_PACKAGE_PATH ="$ROS_PACKAGE_PATH
echo "ROS_PACKAGE_PATH= ROSLISP_PACKAGE_DIRECTORIES ="$ROSLISP_PACKAGE_DIRECTORIES
echo "ROS_ETC_DIR ="$ROS_ETC_DIR
echo "ROS_MASTER_URI="$ROS_MASTER_URI
echo "ROS_LOCALHOST_ONLY="$ROS_LOCALHOST_ONLY
echo "ROS_ROOT="$ROS_ROOT
echo "ROS_DISTRO="$ROS_DISTRO

echo "ไอพีที่ใช้สำหรับเครื่อง Server" $ROS_MASTER_URI
echo "ไอพีที่ใช้สำหรับเครื่องที่ทำหน้าที่เป็นโฮส" $ROS_HOSTNAME

